### ISSUE TITLE
Caption Generation

### ISSUE THREAD

**Issue by jainnipun11** [cuhksz-nlp/R2Gen#28]
Good Morning. How to visualize the predicted caption?

**Comment by zaaachos** [comment]
@jainnipun11 Do you mean to print the predicted caption in each step for each image? Or to store the predicted captions in a CSV (or a file format you want) and then observe the predictions one by one?

**Comment by jainnipun11** [comment]
Hey! Either way will work, I just want to see the predicted captions corresponding to the actual one. Please guide me on how to get them by any one way you mentioned. Thanks.

**Comment by zaaachos** [comment]
@jainnipun11 It's easy. You have to go on this line --> https://github.com/cuhksz-nlp/R2Gen/blob/5a2e63f6d8da670725b1926317b4bfd1393ec51b/modules/trainer.py#L204 as well as in the eval mode of the test set respectively.

Below I will write the new updated code only for the validation set. You have to add the same for the test set (if you want to check the predicted captions for the test set). This code snippet saves the image ids along with their captions in each epoch.

```python     
self.model.eval()
with torch.no_grad():
    val_gts, val_res = [], []
    val_images_list = list()
    for batch_idx, (images_id, images, reports_ids, reports_masks) in enumerate(self.val_dataloader):
        images, reports_ids, reports_masks = images.to(self.device), reports_ids.to(
            self.device), reports_masks.to(self.device)
        output = self.model(images, mode='sample')
        reports = self.model.tokenizer.decode_batch(output.cpu().numpy())
        ground_truths = self.model.tokenizer.decode_batch(reports_ids[:, 1:].cpu().numpy())
        val_res.extend(reports)
        val_gts.extend(ground_truths)
        val_images_list.extend(images_id)
    val_met = self.metric_ftns({i: [gt] for i, gt in enumerate(val_images_list, val_gts)},
                               {i: [re] for i, re in enumerate(val_images_list, val_res)})
    log.update(**{'val_' + k: v for k, v in val_met.items()})
```

Then go to the metrics.py where the self.metric_ftns is being called for each image_id, report pair.

Add in the following code snippet in this line --> https://github.com/cuhksz-nlp/R2Gen/blob/5a2e63f6d8da670725b1926317b4bfd1393ec51b/modules/metrics.py#L4
```python
import pandas as pd
```
Then you have to open a new terminal to install the pandas library. Just write the following:
`
pip3 install pandas (or pip install pandas if you have pip version < 3)
`

Lastly, add the following code snippets in this line --> https://github.com/cuhksz-nlp/R2Gen/blob/5a2e63f6d8da670725b1926317b4bfd1393ec51b/modules/metrics.py#L14

```python
# first save the ground truth captions
df = pd.DataFrame.from_dict(gts, orient="index")
df.to_csv('path/to/your/folder/gold.csv', sep='\t', header=False)

# then save the predicted ones    
df = pd.DataFrame.from_dict(res, orient="index")
df.to_csv('path/to/your/folder/pred.csv', sep='\t', header=False)
```
The aforementioned code snippet saves all image_id, predicted pairs as well as image_id, golds pairs in a CSV format.

DONE!

**Comment by jainnipun11** [comment]
Hey @zaaachos, I followed your instructions but received the following error:

/usr/local/lib/python3.7/dist-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, "
/usr/local/lib/python3.7/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=ResNet101_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet101_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/content/R2Gen/modules/caption_model.py:73: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  beam_ix = ix // vocab_size  # Nxb which beam
Traceback (most recent call last):
  File "main.py", line 124, in <module>
    main()
  File "main.py", line 120, in main
    trainer.train()
  File "/content/R2Gen/modules/trainer.py", line 54, in train
    result = self._train_epoch(epoch)
  File "/content/R2Gen/modules/trainer.py", line 218, in _train_epoch
    val_met = self.metric_ftns({i: [gt] for i, gt in enumerate(val_images_list, val_gts)},

**TypeError: 'list' object cannot be interpreted as an integer**

What else do I modify? Thanks.

**Comment by zaaachos** [comment]
@jainnipun11 my fault sorry. You have to change each enumerate to zip like this.
```python
zip(val_images_list, val_gts)
````

**Comment by jainnipun11** [comment]
Hey @zaaachos, your above suggestions worked amazingly, thank you! Just one more thing, if I want to you MobileNet as a pretrained model, what changes do I have to do? Can you please guide me on that.

Thanks, 
Nipun Jain

**Comment by zaaachos** [comment]
@jainnipun11 Firsty you need to check from the official Pytorch documentation of MobileNet whether it is available for your torchvision version or not. 

Secondly, you need to check if the CUDA version of your GPU (if you run on GPU) is compatible with the Torch version of the MobileNet. I had some issues when I run this code on some CNN models due to the CUDA version of my GPU.  One CNN that indeed works well with this code was DenseNet-121. I will write down the code block you need to change in order to experiment with different models except ResNet101.

First comment-out lines from 11 to 14 on this py file --> https://github.com/cuhksz-nlp/R2Gen/blob/5a2e63f6d8da670725b1926317b4bfd1393ec51b/modules/visual_extractor.py#L11

and add these code block instead:

```python
model = models.densenet121(pretrained = True)     # for DenseNet-121
newmodel = torch.nn.Sequential(*(list(model.children())[:-1]))
self.model = newmodel
self.avg_fnt = torch.nn.AvgPool2d(kernel_size=7, stride=1, padding=0)
```
if you want to experiment with more models please check this [link](https://pytorch.org/vision/main/models.html) .

Lastly, you need to change the parameters of the embeddings depending on the image encoder you will use. 
You have to change this number on this line --> https://github.com/cuhksz-nlp/R2Gen/blob/5a2e63f6d8da670725b1926317b4bfd1393ec51b/main.py#L34

Here 2048 is the dimension of the last average pooling layer of the ResNet101.
For example, for DenseNet-121 you have to substitute it with 1024

**Comment by jainnipun11** [comment]
Hey @zaaachos, thanks for the above steps, they were really helpful. I used MobileNet and was able to get fine results following your words. I'm also trying to run the model without MCLN+RM i.e with just the base. Can you guide me how to do that?

Thanks & Regards,
Nipun

**Comment by zaaachos** [comment]
@jainnipun11 hey 👋. I haven't experienced with this step before. Thus, contact with the authors

**Comment by jainnipun11** [comment]
@zaaachos Okay, sure I will! Thanks for the help.

**Comment by jainnipun11** [comment]
Hey @zaaachos , have you tried running the base model? Can you help with that.

Thanks,
Nipun Jain

**Comment by zaaachos** [comment]
@jainnipun11 hello. You have to download the weights, and find the argument, which loads the path of this weights file, in main.py. Add the file path as default.

More particularly, here --> https://github.com/cuhksz-nlp/R2Gen/blob/5a2e63f6d8da670725b1926317b4bfd1393ec51b/main.py#L83

**Comment by jainnipun11** [comment]
@zaaachos, Which weights file to download exactly?

**Comment by jainnipun11** [comment]
Hey @zaaachos, by base model I meant without Relational Memory. Downloading the weights won't solve this issue right? I mean logically it would still contain weights of parameters involved with RM. Am I getting this right? 

Thanks,
Nipun

**Comment by zaaachos** [comment]
@jainnipun11 I had replied to that question (regarding base model withouth RM) and I told you to ask authors. I hadn't tried that.

**Comment by Liqq1** [comment]
> @jainnipun11 I had replied to that question (regarding base model withouth RM) and I told you to ask authors. I hadn't tried that.

Hi! I'm sorry to bother you. I hope to get your help. 
1.  Have you tried to reproduce the results using the weights provided by the author? I tried this, but the results(On IU X-ray) I got were not the same as those shown in the paper, which is higher than the paper. 
![32671677915599_ pic](https://user-images.githubusercontent.com/54054113/222885315-f0f9ca07-4249-4899-8855-fab593546647.jpg)

2. Results on data set MIMIC-CXR. Why are the results in the following two tables different? The author mentioned "the number of memory slots is set to 3 by default" in the paper, but the results in Table 1 are different from the third row in Table 2, do you know why?
![78a6ffa93affabd391d0a3110576e306](https://user-images.githubusercontent.com/54054113/222885367-681dd5e3-677d-4242-87cc-4a4b3b13baee.png)
![961ca76bab5895ca7412b593206ddf78](https://user-images.githubusercontent.com/54054113/222885371-f0fcbec1-c302-4513-b772-cb5e79f40b89.png)

**Comment by zaaachos** [comment]
@Liqq1 Hey there 😊

2. I am not the author of this paper, thus I don't know what's this about. I have only used this for my research. Likewise, I think it's more appropriate to ask them directly (send an email, as well)!

1. No, due to the fact that they did not use the whole IU-Xray dataset as I did on my research. If you used the pretrained weights on THEIR provided test set, without any modification on the model (even the parameters they use as well as the random seed), I can not explain this difference. It's weird actually..

**Comment by Liqq1** [comment]
> @Liqq1 Hey there 😊
> 
> 2. I am not the author of this paper, thus I don't know what's this about. I have only used this for my research. Likewise, I think it's more appropriate to ask them directly (send an email, as well)!
> 3. No, due to the fact that they did not use the whole IU-Xray dataset as I did on my research. If you used the pretrained weights on THEIR provided test set, without any modification on the model (even the parameters they use as well as the random seed), I can not explain this difference. It's weird actually..

Thanks for your reply!😄
The author probably didn't follow the 'issue' of his project, so I couldn't confirm it with him on github. You're right. I think I should send him an email to confirm.

**Comment by Ammexm** [comment]
> > @jainnipun11 I had replied to that question (regarding base model withouth RM) and I told you to ask authors. I hadn't tried that.
> 
> Hi! I'm sorry to bother you. I hope to get your help.
> 
> 1. Have you tried to reproduce the results using the weights provided by the author? I tried this, but the results(On IU X-ray) I got were not the same as those shown in the paper, which is higher than the paper.
>    ![32671677915599_ pic](https://user-images.githubusercontent.com/54054113/222885315-f0f9ca07-4249-4899-8855-fab593546647.jpg)
> 2. Results on data set MIMIC-CXR. Why are the results in the following two tables different? The author mentioned "the number of memory slots is set to 3 by default" in the paper, but the results in Table 1 are different from the third row in Table 2, do you know why?
>    ![78a6ffa93affabd391d0a3110576e306](https://user-images.githubusercontent.com/54054113/222885367-681dd5e3-677d-4242-87cc-4a4b3b13baee.png)
>    ![961ca76bab5895ca7412b593206ddf78](https://user-images.githubusercontent.com/54054113/222885371-f0fcbec1-c302-4513-b772-cb5e79f40b89.png)

hello~May I ask if the first question you asked has been resolved? Why is the effect of reproducing IU so high?

**Comment by Liqq1** [comment]
> > > @jainnipun11 I had replied to that question (regarding base model withouth RM) and I told you to ask authors. I hadn't tried that.
> > 
> > 
> > Hi! I'm sorry to bother you. I hope to get your help.
> > 
> > 1. Have you tried to reproduce the results using the weights provided by the author? I tried this, but the results(On IU X-ray) I got were not the same as those shown in the paper, which is higher than the paper.
> >    ![32671677915599_ pic](https://user-images.githubusercontent.com/54054113/222885315-f0f9ca07-4249-4899-8855-fab593546647.jpg)
> > 2. Results on data set MIMIC-CXR. Why are the results in the following two tables different? The author mentioned "the number of memory slots is set to 3 by default" in the paper, but the results in Table 1 are different from the third row in Table 2, do you know why?
> >    ![78a6ffa93affabd391d0a3110576e306](https://user-images.githubusercontent.com/54054113/222885367-681dd5e3-677d-4242-87cc-4a4b3b13baee.png)
> >    ![961ca76bab5895ca7412b593206ddf78](https://user-images.githubusercontent.com/54054113/222885371-f0fcbec1-c302-4513-b772-cb5e79f40b89.png)
> 
> hello~May I ask if the first question you asked has been resolved? Why is the effect of reproducing IU so high?

Hello,
At the moment, I haven't received a definitive answer. I suspect that the authors may have rerun the experiments later and achieved better results. In my view, such a scenario is plausible since the metrics for this task are highly volatile, and even the same model can yield very different outcomes with varying parameters or on different machines.

**Comment by zaaachos** [comment]
Hey @Ammexm.
Yes indeed. As @Liqq1 said, working on different resources (in particular, stronger ones) can produce better results. Also, the seeder is also an additional parameter you should take into consideration, when you are working with the same data.

**Comment by rhyhck** [comment]
> @jainnipun11 Do you mean to print the predicted caption in each step for each image? Or to store the predicted captions in a CSV (or a file format you want) and then observe the predictions one by one?

hi~ Do you know how to get the MIMIC-cxr dataset？I try to get it by this"wget -r -N -c -np --user renhongyi --ask-password https://physionet.org/files/mimic-cxr-jpg/2.0.0/" but I can't get it ,as below:
"Resolving physionet.org (physionet.org)... 18.18.42.54
Connecting to physionet.org (physionet.org)|18.18.42.54|:443... failed: Connection timed out.
Retrying."
can you help me? thanks!!

**Comment by zaaachos** [comment]
@rhyhck We had a pre-downloaded version of the MIMIC dataset in my university servers when we worked for our academic research, so I don't have any information here, sorry. However, I think it is accessible with an account only, from their official website.

**Comment by rhyhck** [comment]
> @rhyhck We had a pre-downloaded version of the MIMIC dataset in my university servers when we worked for our academic research, so I don't have any information here, sorry. However, I think it is accessible with an account only, from their official website.

OK！I have got an account, but my net is not so stable that I dont't know whether the dataset is completely downloaded. Could you tell me the size of the every  file? especially the named "files" in the dataset. Thank you very much!

**Comment by zaaachos** [comment]
> > @rhyhck We had a pre-downloaded version of the MIMIC dataset in my university servers when we worked for our academic research, so I don't have any information here, sorry. However, I think it is accessible with an account only, from their official website.
> 
> OK！I have got an account, but my net is not so stable that I dont't know whether the dataset is completely downloaded. Could you tell me the size of the every file? especially the named "files" in the dataset. Thank you very much!

As far as I remember the data consists of 371,920 X-rays, with 227,943 cases and 14 classes. Unfortunately, I no longer have access to the uni server's and I can not see the exact file size. 
 
 You could find information though from this [link](https://github.com/MIT-lcp/mimic-code)

**Comment by rhyhck** [comment]
> > > @rhyhck We had a pre-downloaded version of the MIMIC dataset in my university servers when we worked for our academic research, so I don't have any information here, sorry. However, I think it is accessible with an account only, from their official website.
> > 
> > 
> > OK！I have got an account, but my net is not so stable that I dont't know whether the dataset is completely downloaded. Could you tell me the size of the every file? especially the named "files" in the dataset. Thank you very much!
> 
> As far as I remember the data consists of 371,920 X-rays, with 227,943 cases and 14 classes. Unfortunately, I no longer have access to the uni server's and I can not see the exact file size.
> 
> You could find information though from this [link](https://github.com/MIT-lcp/mimic-code)

OK! Thank you for your help~

**Comment by rhyhck** [comment]
> > > @rhyhck We had a pre-downloaded version of the MIMIC dataset in my university servers when we worked for our academic research, so I don't have any information here, sorry. However, I think it is accessible with an account only, from their official website.
> > 
> > 
> > OK！I have got an account, but my net is not so stable that I dont't know whether the dataset is completely downloaded. Could you tell me the size of the every file? especially the named "files" in the dataset. Thank you very much!
> 
> As far as I remember the data consists of 371,920 X-rays, with 227,943 cases and 14 classes. Unfortunately, I no longer have access to the uni server's and I can not see the exact file size.
> 
> You could find information though from this [link](https://github.com/MIT-lcp/mimic-code)

Hello, if I want to take any image as input and output the corresponding report through R2Gen, how can I achieve it? How can I avoid training and directly use ready-made image testing?

**Comment by zaaachos** [comment]
> > > > @rhyhck We had a pre-downloaded version of the MIMIC dataset in my university servers when we worked for our academic research, so I don't have any information here, sorry. However, I think it is accessible with an account only, from their official website.
> > > 
> > > 
> > > OK！I have got an account, but my net is not so stable that I dont't know whether the dataset is completely downloaded. Could you tell me the size of the every file? especially the named "files" in the dataset. Thank you very much!
> > 
> > 
> > As far as I remember the data consists of 371,920 X-rays, with 227,943 cases and 14 classes. Unfortunately, I no longer have access to the uni server's and I can not see the exact file size.
> > You could find information though from this [link](https://github.com/MIT-lcp/mimic-code)
> 
> Hello, if I want to take any image as input and output the corresponding report through R2Gen, how can I achieve it? How can I avoid training and directly use ready-made image testing?

You will find the answer at the beginning of this thread. Firstly, you have to download the weights and load the path of it, directly at the args parameter of the main.py. Then, you have to initialize a single image dataset if you want to test it out, or just use naive Pytorch with inference stage.

A great course for Pytorch I recently finished is ![this](https://www.learnpytorch.io/). You will find great explanation for training and testing you are requesting

**Comment by rhyhck** [comment]
> > > > > @rhyhck We had a pre-downloaded version of the MIMIC dataset in my university servers when we worked for our academic research, so I don't have any information here, sorry. However, I think it is accessible with an account only, from their official website.
> > > > 
> > > > 
> > > > OK！I have got an account, but my net is not so stable that I dont't know whether the dataset is completely downloaded. Could you tell me the size of the every file? especially the named "files" in the dataset. Thank you very much!
> > > 
> > > 
> > > As far as I remember the data consists of 371,920 X-rays, with 227,943 cases and 14 classes. Unfortunately, I no longer have access to the uni server's and I can not see the exact file size.
> > > You could find information though from this [link](https://github.com/MIT-lcp/mimic-code)
> > 
> > 
> > Hello, if I want to take any image as input and output the corresponding report through R2Gen, how can I achieve it? How can I avoid training and directly use ready-made image testing?
> 
> You will find the answer at the beginning of this thread. Firstly, you have to download the weights and load the path of it, directly at the args parameter of the main.py. Then, you have to initialize a single image dataset if you want to test it out, or just use naive Pytorch with inference stage.
> 
> A great course for Pytorch I recently finished is ![this](https://camo.githubusercontent.com/f5d7cc00922add9f61883eca89a2c59b83ba9f3215606c6492bb8db0fc04ae8b/68747470733a2f2f7777772e6c6561726e7079746f7263682e696f2f). You will find great explanation for training and testing you are requesting

Sorry, I was dealing with an urgent matter a few days ago. Thank you very much for your reply. I tried the method you mentioned earlier on this line, but encountered some problems. Can you help me take a look? I think email communication is more convenient. May I have your email address? thanks

**Comment by rhyhck** [comment]
> @jainnipun11 It's easy. You have to go on this line -->
> 
> https://github.com/cuhksz-nlp/R2Gen/blob/5a2e63f6d8da670725b1926317b4bfd1393ec51b/modules/trainer.py#L204
> 
> as well as in the eval mode of the test set respectively.
> Below I will write the new updated code only for the validation set. You have to add the same for the test set (if you want to check the predicted captions for the test set). This code snippet saves the image ids along with their captions in each epoch.
> 
> ```python
> self.model.eval()
> with torch.no_grad():
>     val_gts, val_res = [], []
>     val_images_list = list()
>     for batch_idx, (images_id, images, reports_ids, reports_masks) in enumerate(self.val_dataloader):
>         images, reports_ids, reports_masks = images.to(self.device), reports_ids.to(
>             self.device), reports_masks.to(self.device)
>         output = self.model(images, mode='sample')
>         reports = self.model.tokenizer.decode_batch(output.cpu().numpy())
>         ground_truths = self.model.tokenizer.decode_batch(reports_ids[:, 1:].cpu().numpy())
>         val_res.extend(reports)
>         val_gts.extend(ground_truths)
>         val_images_list.extend(images_id)
>     val_met = self.metric_ftns({i: [gt] for i, gt in enumerate(val_images_list, val_gts)},
>                                {i: [re] for i, re in enumerate(val_images_list, val_res)})
>     log.update(**{'val_' + k: v for k, v in val_met.items()})
> ```
> 
> Then go to the metrics.py where the self.metric_ftns is being called for each image_id, report pair.
> 
> Add in the following code snippet in this line -->
> 
> https://github.com/cuhksz-nlp/R2Gen/blob/5a2e63f6d8da670725b1926317b4bfd1393ec51b/modules/metrics.py#L4
> 
> ```python
> import pandas as pd
> ```
> 
> Then you have to open a new terminal to install the pandas library. Just write the following: `pip3 install pandas (or pip install pandas if you have pip version < 3)`
> 
> Lastly, add the following code snippets in this line -->
> 
> https://github.com/cuhksz-nlp/R2Gen/blob/5a2e63f6d8da670725b1926317b4bfd1393ec51b/modules/metrics.py#L14
> 
> ```python
> # first save the ground truth captions
> df = pd.DataFrame.from_dict(gts, orient="index")
> df.to_csv('path/to/your/folder/gold.csv', sep='\t', header=False)
> 
> # then save the predicted ones    
> df = pd.DataFrame.from_dict(res, orient="index")
> df.to_csv('path/to/your/folder/pred.csv', sep='\t', header=False)
> ```
> 
> The aforementioned code snippet saves all image_id, predicted pairs as well as image_id, golds pairs in a CSV format.
> 
> DONE!

Hello, after adding the above code according to your prompt, I encountered the following problem. Can you tell me how to modify it? thanks。

Loading checkpoint: model_iu_xray.pth ...
Checkpoint loaded. Resume training from epoch 15
Traceback (most recent call last):
  File "main.py", line 125, in <module>
    main()
  File "main.py", line 121, in main
    trainer.train()
  File "/data/renhongyi/R2Gen/R2Gen-main/modules/trainer.py", line 54, in train
    result = self._train_epoch(epoch)  #返回训练、验证、测试集之后的log
  File "/data/renhongyi/R2Gen/R2Gen-main/modules/trainer.py", line 229, in _train_epoch
    {i: [re] for i, re in enumerate(zip(val_images_list,val_res))})
  File "/data/renhongyi/R2Gen/R2Gen-main/modules/metrics.py", line 33, in compute_scores
    score, scores = scorer.compute_score(gts, res, verbose=0)
  File "/data/renhongyi/R2Gen/R2Gen-main/pycocoevalcap/bleu/bleu.py", line 49, in compute_score
    bleu_scorer += (hypo[0], ref)
  File "/data/renhongyi/R2Gen/R2Gen-main/pycocoevalcap/bleu/bleu_scorer.py", line 171, in __iadd__
    self.cook_append(other[0], other[1])
  File "/data/renhongyi/R2Gen/R2Gen-main/pycocoevalcap/bleu/bleu_scorer.py", line 118, in cook_append
    self.crefs.append(cook_refs(refs))
  File "/data/renhongyi/R2Gen/R2Gen-main/pycocoevalcap/bleu/bleu_scorer.py", line 45, in cook_refs
    rl, counts = precook(ref, n)
  File "/data/renhongyi/R2Gen/R2Gen-main/pycocoevalcap/bleu/bleu_scorer.py", line 29, in precook
    words = s.split()
AttributeError: 'tuple' object has no attribute 'split'

**Comment by zaaachos** [comment]
@rhyhck You have to provide me more details about your problem. I suppose something is missing from your data

**Comment by LiuAoBo2020** [comment]
> > > > @rhyhck We had a pre-downloaded version of the MIMIC dataset in my university servers when we worked for our academic research, so I don't have any information here, sorry. However, I think it is accessible with an account only, from their official website.当我们为学术研究工作时，在我的大学服务器上有一个预先下载的MIMIC数据集版本，所以我在这里没有任何信息，抱歉。但是，我认为只有在他们的官方网站上有账户才能访问。
> > > 
> > > 
> > > OK！I have got an account, but my net is not so stable that I dont't know whether the dataset is completely downloaded. Could you tell me the size of the every file? especially the named "files" in the dataset. Thank you very much!好的!我有一个账号，但是我的网络不太稳定，我不知道数据集是否下载完整。你能告诉我每个文件的大小吗?特别是数据集中命名的“文件”。非常感谢!
> > 
> > 
> > As far as I remember the data consists of 371,920 X-rays, with 227,943 cases and 14 classes. Unfortunately, I no longer have access to the uni server's and I can not see the exact file size.据我所知，数据包括371,920张x光片，227,943例，14类。不幸的是，我不再有访问单一服务器的，我不能看到确切的文件大小。
> > You could find information though from this [link](https://github.com/MIT-lcp/mimic-code)你可以通过这个链接找到相关信息
> 
> Hello, if I want to take any image as input and output the corresponding report through R2Gen, how can I achieve it? How can I avoid training and directly use ready-made image testing?你好，如果我想把任意一张图片作为输入，通过R2Gen输出相应的报告，我该如何实现?如何避免培训，直接使用现成的形象测试?



> > > > @rhyhck We had a pre-downloaded version of the MIMIC dataset in my university servers when we worked for our academic research, so I don't have any information here, sorry. However, I think it is accessible with an account only, from their official website.
> > > 
> > > 
> > > OK！I have got an account, but my net is not so stable that I dont't know whether the dataset is completely downloaded. Could you tell me the size of the every file? especially the named "files" in the dataset. Thank you very much!
> > 
> > 
> > As far as I remember the data consists of 371,920 X-rays, with 227,943 cases and 14 classes. Unfortunately, I no longer have access to the uni server's and I can not see the exact file size.
> > You could find information though from this [link](https://github.com/MIT-lcp/mimic-code)
> 
> Hello, if I want to take any image as input and output the corresponding report through R2Gen, how can I achieve it? How can I avoid training and directly use ready-made image testing?

hello，I would like to ask how to implement this, do I need to run main.py script

**Comment by Labqw** [comment]
> > > > @rhyhck We had a pre-downloaded version of the MIMIC dataset in my university servers when we worked for our academic research, so I don't have any information here, sorry. However, I think it is accessible with an account only, from their official website.当我们为学术研究工作时，在我的大学服务器上有一个预先下载的MIMIC数据集版本，所以我在这里没有任何信息，抱歉。但是，我认为只有在他们的官方网站上有账户才能访问。
> > > 
> > > 
> > > OK！I have got an account, but my net is not so stable that I dont't know whether the dataset is completely downloaded. Could you tell me the size of the every file? especially the named "files" in the dataset. Thank you very much!好的!我有一个账号，但是我的网络不太稳定，我不知道数据集是否下载完整。你能告诉我每个文件的大小吗?特别是数据集中命名的“文件”。非常感谢!
> > 
> > 
> > As far as I remember the data consists of 371,920 X-rays, with 227,943 cases and 14 classes. Unfortunately, I no longer have access to the uni server's and I can not see the exact file size.据我所知，数据包括371,920张x光片，227,943例，14类。不幸的是，我不再有访问单一服务器的，我不能看到确切的文件大小。
> > You could find information though from this [link](https://github.com/MIT-lcp/mimic-code)你可以通过这个链接找到相关信息
> 
> Hello, if I want to take any image as input and output the corresponding report through R2Gen, how can I achieve it? How can I avoid training and directly use ready-made image testing?你好，如果我想把任意一张图片作为输入，通过R2Gen输出相应的报告，我该如何实现?如何避免培训，直接使用现成的形象测试?



> > > > @rhyhck We had a pre-downloaded version of the MIMIC dataset in my university servers when we worked for our academic research, so I don't have any information here, sorry. However, I think it is accessible with an account only, from their official website.
> > > 
> > > 
> > > OK！I have got an account, but my net is not so stable that I dont't know whether the dataset is completely downloaded. Could you tell me the size of the every file? especially the named "files" in the dataset. Thank you very much!
> > 
> > 
> > As far as I remember the data consists of 371,920 X-rays, with 227,943 cases and 14 classes. Unfortunately, I no longer have access to the uni server's and I can not see the exact file size.
> > You could find information though from this [link](https://github.com/MIT-lcp/mimic-code)
> 
> Hello, if I want to take any image as input and output the corresponding report through R2Gen, how can I achieve it? How can I avoid training and directly use ready-made image testing?

Hello,how to implement this?

**Comment by Labqw** [comment]
> > > > > @rhyhck We had a pre-downloaded version of the MIMIC dataset in my university servers when we worked for our academic research, so I don't have any information here, sorry. However, I think it is accessible with an account only, from their official website.当我们为学术研究工作时，在我的大学服务器上有一个预先下载的MIMIC数据集版本，所以我在这里没有任何信息，抱歉。但是，我认为只有在他们的官方网站上有账户才能访问。
> > > > 
> > > > 
> > > > OK！I have got an account, but my net is not so stable that I dont't know whether the dataset is completely downloaded. Could you tell me the size of the every file? especially the named "files" in the dataset. Thank you very much!好的!我有一个账号，但是我的网络不太稳定，我不知道数据集是否下载完整。你能告诉我每个文件的大小吗?特别是数据集中命名的“文件”。非常感谢!
> > > 
> > > 
> > > As far as I remember the data consists of 371,920 X-rays, with 227,943 cases and 14 classes. Unfortunately, I no longer have access to the uni server's and I can not see the exact file size.据我所知，数据包括371,920张x光片，227,943例，14类。不幸的是，我不再有访问单一服务器的，我不能看到确切的文件大小。
> > > You could find information though from this [link](https://github.com/MIT-lcp/mimic-code)你可以通过这个链接找到相关信息
> > 
> > 
> > Hello, if I want to take any image as input and output the corresponding report through R2Gen, how can I achieve it? How can I avoid training and directly use ready-made image testing?你好，如果我想把任意一张图片作为输入，通过R2Gen输出相应的报告，我该如何实现?如何避免培训，直接使用现成的形象测试?
> 
> You will find the answer at the beginning of this thread. Firstly, you have to download the weights and load the path of it, directly at the args parameter of the main.py. Then, you have to initialize a single image dataset if you want to test it out, or just use naive Pytorch with inference stage.你会在这个帖子的开头找到答案。首先，您必须下载权重并加载它的路径，直接在main.py的args参数处加载。然后，如果你想测试它，你必须初始化一个图像数据集，或者只是使用朴素的Pytorch和推理阶段。
> 
> A great course for Pytorch I recently finished is ![this](https://camo.githubusercontent.com/c03b1bc358bec962b2742dcd3dc3394af20e1d423c3a90b2dc35210d4598988a/68747470733a2f2f7777772e6c6561726e7079746f7263682e696f2f). You will find great explanation for training and testing you are requesting我最近完成的Pytorch的一门很棒的课程是。您将找到您所要求的培训和测试的很好的解释



> @jainnipun11 Do you mean to print the predicted caption in each step for each image? Or to store the predicted captions in a CSV (or a file format you want) and then observe the predictions one by one?

Hello,How can I use the model to generate a report on any X-ray?
