### ISSUE TITLE
Calculation of clinical accuracy for MIMIC dataset

### ISSUE THREAD

**Issue by ashwanikumar04** [cuhksz-nlp/R2Gen#8]
Hello:

Thanks for sharing the code.

While going through the code, I did not find the code that calculates the clinal accuracy (Precision, Recall, and F1) metrics calculation. 
Will it be possible to share that?

Thanks

**Comment by zhjohnchan** [comment]
Dear @ashwanikumar04,

Thanks for your attention to our paper!

We directly used the CheXpert labeler (https://github.com/MIT-LCP/mimic-cxr/
tree/master/txt/chexpert) to label the generated and ground-truth reports and then compute the precision, recall, and F1.

Best,
Zhihong

**Comment by ashwanikumar04** [comment]
Thanks for the reply. I am trying to use the same. However, the labeler is failing with this error. I am using ubuntu with python 3.6

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from bllipparser import RerankingParser
  File "/home/ubuntu/.conda/envs/chexpert-label/lib/python3.6/site-packages/bllipparser/__init__.py", line 399, in <module>
    from .RerankingParser import RerankingParser, Tree, Sentence, tokenize
  File "/home/ubuntu/.conda/envs/chexpert-label/lib/python3.6/site-packages/bllipparser/RerankingParser.py", line 20, in <module>
    from . import JohnsonReranker as reranker
  File "/home/ubuntu/.conda/envs/chexpert-label/lib/python3.6/site-packages/bllipparser/JohnsonReranker.py", line 28, in <module>
    _JohnsonReranker = swig_import_helper()
  File "/home/ubuntu/.conda/envs/chexpert-label/lib/python3.6/site-packages/bllipparser/JohnsonReranker.py", line 24, in swig_import_helper
    _mod = imp.load_module('_JohnsonReranker', fp, pathname, description)
  File "/home/ubuntu/.conda/envs/chexpert-label/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/ubuntu/.conda/envs/chexpert-label/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/ubuntu/.conda/envs/chexpert-label/lib/python3.6/site-packages/bllipparser/_JohnsonReranker.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev

```

**Comment by Otiss-pang** [comment]
> Hello:
> 
> Thanks for sharing the code.
> 
> While going through the code, I did not find the code that calculates the clinal accuracy (Precision, Recall, and F1) metrics calculation. Will it be possible to share that?
> 
> Thanks

Hello, did you know how to get the code for clinical accuracy (Precision, Recall, and F1) , I used the Chexpert to get the label, but I dont know how to calculate the accuracy.
If you do know, could you plz share the code? 

Thanks.
